# Generated by Django 3.1.7 on 2021-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categorie_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('site', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('contact_technical_manager', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
